<div id="kuler-slide-<?php echo $module; ?>" class="kuler-slides">
	<div class="box kuler-module">
		<?php if ($show_title) { ?>
			<div class="box-heading"><span><?php echo $module_title ?></span></div>
		<?php } ?>
		<div class="jcarousel-skin-opencart">
			<ul id="kulerslides<?php echo $module + 1 ?>" class="kuler-slides-content">
				<?php foreach ($products as $key => $slides) { ?>
					<li id="kuler-slide-<?php echo $module + 1, $key + 1; ?>">
						<div class="box-product product-grid">
							<?php foreach ($slides as $product) { ?>
								<?php echo $this->loadChromeTemplate($setting, $product); ?>
							<?php } ?>
						</div>
					</li>
				<?php } ?>
			</ul>
		</div>
	</div>
</div>

<?php if (!empty($products)) { ?>
<script type="text/javascript">
$(document).ready(function() {
    $("#kuler-slide-<?php echo $module; ?> .kuler-slides-content").jcarousel({
	    <?php if (count($products) <= 1) { ?>
	    buttonNextHTML: '',
	    buttonPrevHTML: '',
	    <?php } ?>
        vertical: false,
        visible: 1,
        scroll: 1
    });
});
</script>
<?php } ?>